before_script:
  - export NEPC_HOME=$CI_PROJECT_DIR
  - conda env remove --name nepc
  - conda env create -f environment.yml
  - conda activate nepc
  - pip install pylint-exit
  - pip install anybadge
  - pip install docstr-coverage
  - pip install -e .

stages:
  - pytest
  - pylint
  - sphinx

pytest:
  stage: pytest
  tags:
    - linux
    - mysql
    - python
  script:
    - pytest --cov=nepc tests/

pylint:
  stage: pylint
  tags:
    - linux
    - python
  script:
    - pylint --output-format=text nepc/ | tee pylint.txt || pylint-exit $?
    - score=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylint.txt)
    - echo "Pylint score was $score"
    - anybadge --value=$score --file=public/pylint.svg pylint
  artifacts:
    paths:
      - public/pylint.svg

sphinx:
  stage: sphinx
  tags:
    - linux
    - python
  script:
    - cd doc
    - make html
    - rsync -rl _build/html/ /srv/shiny-server/nepc/doc/ --delete
    - cd $NEPC_HOME
    - docstr-coverage nepc > docstr.txt
    - score=$(sed -n 's/^Total docstring coverage: \([-0-9.]*\)\/.*/\1/p' docstr.txt)
    - echo "docstr-coverage score was $score"
    - anybadge --value=$score --file=public/docstr_coverage.svg doc
  artifacts:
    paths:
      - public/docstr-coverage.svg
