before_script:
  - export NEPC_HOME=$CI_PROJECT_DIR
  - conda env create -f environment.yml
  - pip install -e .
  - conda activate nepc

stages:
  - test
  - lint

pytest:
  stage: test
  tags:
    - linux
    - mysql
    - python
  script:
    - pytest --cov=nepc tests/

pylint:
  stage: lint
  tags:
    - linux
    - python
  script:
    - pylint --output-format=text nepc/ | tee pylint.txt || pylint-exit $?
    - score=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylint.txt)
    - echo "Pylint score was $score"
    - anybadge --value=$score --file=public/pylint.svg pylint
  artifacts:
    paths:
      - public/pylint.svg
