before_script:
  - export NEPC_HOME=$CI_PROJECT_DIR
  - conda activate nepc

stages:
  - test
  - lint

pytest:
  stage: test
  tags:
    - linux
    - mysql
    - python
  script:
    - pytest --cov=nepc tests/

pylint:
  stage: lint
  tags:
    - linux
    - python
  script:
    - pylint nepc/
